# Generated by Django 4.2.2 on 2023-08-02 13:24

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import home.cliente.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id_chat', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateField()),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Chat',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id_cita', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_motivo', models.CharField(max_length=200, verbose_name='Motivo de cita')),
                ('fecha_creacion', models.DateTimeField(verbose_name='Fecha de Creacion')),
                ('fecha_inicioatencion', models.DateTimeField(null=True, verbose_name='Fecha Inicio de Atención')),
                ('fecha_finatencion', models.DateTimeField(verbose_name='Fecha Fin de Atención')),
                ('latitud', models.DecimalField(decimal_places=9, max_digits=15)),
                ('longitud', models.DecimalField(decimal_places=9, max_digits=15)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'Cita',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClasificacionDeEnfermerdades',
            fields=[
                ('idclasificacion', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción')),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Clasif. de Enfermedades',
                'verbose_name_plural': 'Clasif. de Enfermedades',
                'db_table': 'Clasificacion_de_enfermerdades',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=10, unique=True, verbose_name='Cédula')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('fecha_nacimiento', models.DateField(validators=[home.cliente.models.Cliente.validate_date_range])),
                ('telefono', models.CharField(max_length=10, verbose_name='Teléfono')),
                ('referencia_de_domicilio', models.CharField(max_length=30)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.ciudad')),
            ],
            options={
                'db_table': 'Cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Enfermedades',
            fields=[
                ('id_enfermedad', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción')),
                ('estado', models.BooleanField()),
                ('id_clasificacionenfermedad', models.ForeignKey(db_column='id_clasificacionenfermedad', on_delete=django.db.models.deletion.DO_NOTHING, to='home.clasificaciondeenfermerdades', verbose_name='Id Clasf. Enfermedad')),
            ],
            options={
                'verbose_name': 'Enfermedades',
                'verbose_name_plural': 'Enfermedades',
                'db_table': 'Enfermedades',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstadoCita',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Estado_cita',
                'verbose_name_plural': 'Estado_cita',
                'db_table': 'Estado_cita',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstadoTrabajador',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Estado_trabajador',
                'verbose_name_plural': 'Estado_trabajador',
                'db_table': 'Estado_trabajador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Marker1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profesiones',
            fields=[
                ('id_profesiones', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=70, verbose_name='Descripción')),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Profesiones',
                'verbose_name_plural': 'Profesiones',
                'db_table': 'Profesiones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id_sexo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, verbose_name='Sexo')),
            ],
            options={
                'verbose_name': 'Sexo',
                'verbose_name_plural': 'Sexo',
                'db_table': 'Sexo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoSangre',
            fields=[
                ('id_tiposangre', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50, verbose_name='Tipo de Sangre')),
            ],
            options={
                'verbose_name': 'TipoSangre',
                'verbose_name_plural': 'TipoSangre',
                'db_table': 'TipoSangre',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoTrabajador',
            fields=[
                ('id_tipotrabajador', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=70, verbose_name='Descripción')),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Tipo de Trabajador',
                'verbose_name_plural': 'Tipo de Trabajador',
                'db_table': 'Tipo_trabajador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id_trabajador', models.AutoField(primary_key=True, serialize=False)),
                ('pdf_cedula', models.FileField(null=True, upload_to='pdfs/', verbose_name='Pdf Cédula')),
                ('pdf_curriculum', models.FileField(null=True, upload_to='pdfs/', verbose_name='Pdf Curriculum')),
                ('latitud', models.DecimalField(decimal_places=9, max_digits=15)),
                ('longitud', models.DecimalField(decimal_places=9, max_digits=15)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('presentacion', models.CharField(max_length=200, null=True)),
                ('estado', models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.DO_NOTHING, to='home.estadotrabajador', verbose_name='Estado_Trabajador')),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='home.cliente', verbose_name='Trabajador')),
                ('id_tipo_trabajador', models.ForeignKey(db_column='id_tipo_trabajador', on_delete=django.db.models.deletion.DO_NOTHING, to='home.tipotrabajador', verbose_name='Tipo de Trabajador')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajador',
                'db_table': 'Trabajador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('id_ubicaciones', models.AutoField(primary_key=True, serialize=False)),
                ('latitud', models.DecimalField(decimal_places=9, max_digits=15)),
                ('longitud', models.DecimalField(decimal_places=9, max_digits=15)),
                ('ubicacion', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('estado', models.BooleanField()),
                ('id_trabajador', models.ForeignKey(db_column='id_trabajador', on_delete=django.db.models.deletion.DO_NOTHING, to='home.trabajador')),
            ],
            options={
                'db_table': 'Ubicaciones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id_sucursal', models.AutoField(primary_key=True, serialize=False)),
                ('coordenadas_x', models.DecimalField(decimal_places=6, max_digits=6)),
                ('coordenadas_y', models.DecimalField(decimal_places=7, max_digits=7)),
                ('telefono', models.CharField(max_length=20)),
                ('referencia', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=50)),
                ('pdf_certificadoruc', models.FileField(upload_to='')),
                ('foto', models.ImageField(upload_to='')),
                ('id_trabajador', models.ForeignKey(db_column='id_trabajador', on_delete=django.db.models.deletion.DO_NOTHING, to='home.trabajador')),
            ],
            options={
                'db_table': 'Sucursal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('estado', models.BooleanField()),
                ('id_profesiones', models.ForeignKey(db_column='id_profesiones', on_delete=django.db.models.deletion.DO_NOTHING, to='home.profesiones')),
            ],
            options={
                'db_table': 'Servicio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('id_pais', models.ForeignKey(db_column='id_pais', on_delete=django.db.models.deletion.DO_NOTHING, to='home.pais')),
            ],
        ),
        migrations.CreateModel(
            name='ProfesionesxTrabajador',
            fields=[
                ('id_profesionesxtrabajador', models.AutoField(primary_key=True, serialize=False)),
                ('numero_titulo', models.CharField(max_length=50)),
                ('estado', models.BooleanField()),
                ('id_profesiones', models.ForeignKey(db_column='id_profesiones', on_delete=django.db.models.deletion.DO_NOTHING, to='home.profesiones')),
                ('id_trabajador', models.ForeignKey(db_column='id_trabajador', on_delete=django.db.models.deletion.DO_NOTHING, to='home.trabajador')),
            ],
            options={
                'db_table': 'ProfesionesxTrabajador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_envio', models.DateField()),
                ('Mensaje', models.CharField(max_length=200)),
                ('tipo_mensaje', models.CharField(max_length=50)),
                ('estado_tipo', models.CharField(max_length=50)),
                ('id_chat', models.ForeignKey(db_column='id_chat', on_delete=django.db.models.deletion.DO_NOTHING, to='home.chat')),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='home.cliente')),
            ],
            options={
                'db_table': 'Mensaje',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id_login', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=50, unique=True)),
                ('contrasenia', models.CharField(max_length=50)),
                ('tipo_login', models.CharField(max_length=50)),
                ('estado', models.BooleanField()),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='home.cliente')),
            ],
            options={
                'db_table': 'Login',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GaleriaTrabajador',
            fields=[
                ('id_galeria', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('id_trabajador', models.ForeignKey(db_column='id_trabajador', on_delete=django.db.models.deletion.DO_NOTHING, to='home.trabajador')),
            ],
            options={
                'db_table': 'GaleriaTrabajador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EnfermedadesxPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción')),
                ('estado', models.BooleanField()),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='home.cliente', verbose_name='Cliente')),
                ('id_enfermedad', models.ForeignKey(db_column='id_enfermedad', on_delete=django.db.models.deletion.DO_NOTHING, to='home.enfermedades', verbose_name='Enfermedad')),
            ],
            options={
                'verbose_name': 'Enfermedades x Paciente',
                'verbose_name_plural': 'Enfermedades x Paciente',
                'db_table': 'EnfermedadesxPaciente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField()),
                ('id_sucursal', models.ForeignKey(db_column='id_sucursal', on_delete=django.db.models.deletion.DO_NOTHING, to='home.sucursal')),
                ('id_trabajador', models.ForeignKey(db_column='id_trabajador', on_delete=django.db.models.deletion.DO_NOTHING, to='home.trabajador')),
            ],
            options={
                'db_table': 'DetalleSucursal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleCita',
            fields=[
                ('id_detalle_cita', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_motivo', models.CharField(max_length=200)),
                ('id_cita', models.ForeignKey(db_column='id_cita', on_delete=django.db.models.deletion.DO_NOTHING, to='home.cita')),
                ('id_servicio', models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.DO_NOTHING, to='home.servicio')),
            ],
            options={
                'db_table': 'Detalle_cita',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('login', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='home.login')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.pais', verbose_name='País'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.provincia'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sexo',
            field=models.ForeignKey(db_column='id_sexo', on_delete=django.db.models.deletion.DO_NOTHING, to='home.sexo', verbose_name='Sexo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_sangre',
            field=models.ForeignKey(db_column='id_tiposangre', on_delete=django.db.models.deletion.DO_NOTHING, to='home.tiposangre', verbose_name='Tipo de Sangre'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.provincia'),
        ),
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.ForeignKey(db_column='id_estado', on_delete=django.db.models.deletion.DO_NOTHING, to='home.estadocita', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='cita',
            name='id_cliente',
            field=models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='home.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='cita',
            name='id_trabajador',
            field=models.ForeignKey(db_column='id_trabajador', on_delete=django.db.models.deletion.DO_NOTHING, to='home.trabajador', verbose_name='Trabajador'),
        ),
        migrations.CreateModel(
            name='ChatDetalle',
            fields=[
                ('id_chatdetalle', models.AutoField(primary_key=True, serialize=False)),
                ('id_chat', models.ForeignKey(db_column='id_chat', on_delete=django.db.models.deletion.DO_NOTHING, to='home.chat')),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='home.cliente')),
            ],
            options={
                'db_table': 'ChatDetalle',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='chat',
            name='id_cliente',
            field=models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='home.cliente'),
        ),
        migrations.AddField(
            model_name='chat',
            name='id_trabajador',
            field=models.ForeignKey(db_column='id_trabajador', on_delete=django.db.models.deletion.DO_NOTHING, to='home.trabajador'),
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField()),
                ('comentario', models.CharField(max_length=200)),
                ('id_paciente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.DO_NOTHING, to='home.cliente', verbose_name='Cliente')),
                ('id_trabajador', models.ForeignKey(db_column='id_trabajador', on_delete=django.db.models.deletion.DO_NOTHING, to='home.trabajador', verbose_name='Trabajador')),
            ],
            options={
                'verbose_name_plural': 'Calificación de Atención',
                'db_table': 'Calificacion',
                'managed': True,
            },
        ),
    ]
