"""
Django settings for myapp project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

if os.name == 'nt':
    VENV_BASE = os.environ['VIRTUAL_ENV']
    os.environ['PATH'] = os.path.join(VENV_BASE, 'Lib\\site-packages\\osgeo') + ';' + os.environ['PATH']
    os.environ['PROJ_LIB'] = os.path.join(VENV_BASE, 'Lib\\site-packages\\osgeo\\data\\proj') + ';' + os.environ['PATH']

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)kqd0c802&ouv$f$7i_!xfg*#dw94mi%y_sxwct&8vc6ha6ej1'
#GEOS_LIBRARY_PATH = '/usr/local/lib/libgeos_c.so'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['2f43-45-71-186-236.ngrok-free.app','127.0.0.1']
#ALLOWED_HOSTS = ['*']


# Application definition


INSTALLED_APPS = [
    'jazzmin',
    'home',
    'rest_framework',
    'django_countries',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'openpyxl'

]



JAZZMIN_SETTINGS = {
    "site_title": "UbicMedic Admin",
    "site_header": "UbicMedic",
    "site_brand": "UbicMedic",
    "site_logo": "img/logo.png",
    "copyright": "Play",
    "welcome_sign": "UBICMEDIC",
    #"site_logo": "books/img/salud64.png",
    #"hide_apps": ["auth","home"],
    "hide_apps": ["auth","Autenticación y autorización"],
    #"hide_apps": ["auth","Panel de control"],
    #"site_logo": "books/img/salud64.png",
     "usermenu_links": [
            # {"name": "Alofoke", "url": "https://www.youtube.com/watch?v=BV2j3yjC_DQ", "new_window": True},
            {"model": "auth.user"}
        ],
    #  "usermenu_links": [
    #         {"name": "Alofoke", "url": "...index.html", "new_window": True},
    #         {"model": "auth.user"}
    #     ],
    # Ocultarmodelos
    "hide_models": ["auth.group"], 
    #"show_sidebar": True,
    #"navigation_expanded": True,
    'icons':{
        'home.Cita':'fas fa-plus-circle',
        'home.Calificacion':'fas fa-user-check',
        'home.ClasificacionDeEnfermerdades':'fas fa-project-diagram',
        'home.Cliente':'fas fa-user',
        'home.Servicio':'fas fa-sticky-note',
        'home.trabajador':'fas fa-user-md',
        'home.Enfermedades':'fas fa-heartbeat',
        'home.EnfermedadesxPaciente':'fas fa-head-side-mask',
        'home.Profesiones':'fas fa-users',
        
        'home.TipoTrabajador':'fas fa-user-check',
    }
}

MIDDLEWARE = [
      'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'myapp.middleware.CustomCsrfViewMiddleware'
]

ROOT_URLCONF = 'myapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": "UBICMEDIC1",
        "USER": "postgres",
        "PASSWORD": "123",
        "HOST": "localhost",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'es-ec'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'home', 'static')]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
